import Foundation

/// Subtitle languages, saving, and conversion of JSON subtitles (bilibili's, YouTube's json3) to SRT.
public enum Subtitles {
    /// Language key (`zh-Hans`, `en-US`, `ai-En`) → (ISO 639-2 code, display name).
    public static func languageInfo(_ rawKey: String) -> (code: String, name: String) {
        var key = rawKey
        // zh-hans → zh-Hans
        if let m = key.firstMatch(of: /-[a-z]/) {
            key = key.replacingOccurrences(of: String(m.output), with: String(m.output).uppercased())
        }
        return languageTable[key] ?? ("und", "Undetermined")
    }

    static let languageTable: [String: (String, String)] = [
        "ai-Zh": ("chi", "中文（简体, AI识别）"), "ai-En": ("eng", "English(generated by ai)"),
        "zh-CN": ("chi", "中文（简体）"), "zh-HK": ("chi", "中文（香港繁體）"), "zh-Hans": ("chi", "中文（简体）"),
        "zh-TW": ("chi", "中文（台灣繁體）"), "zh-Hant": ("chi", "中文（繁體）"), "en-US": ("eng", "English(USA)"),
        "ja": ("jpn", "日本語"), "ko": ("kor", "한국어"), "zh-SG": ("chi", "中文（新加坡）"),
        "ab": ("abk", "Аҳәынҭқарра"), "aa": ("aar", "Qafár af"), "af": ("afr", "Afrikaans"), "sq": ("alb", "Gjuha shqipe"),
        "ase": ("ase", "American Sign Language"), "am": ("amh", "አማርኛ"), "arc": ("arc", "ܐܪܡܝܐ"), "hy": ("arm", "հայերեն"),
        "as": ("asm", "অসমীয়া"), "ay": ("aym", "Aymar aru"), "az": ("aze", "Azərbaycan"), "bn": ("ben", "বাংলা ভাষার"),
        "ba": ("bak", "Башҡорттеле"), "eu": ("baq", "Euskara"), "be": ("bel", "беларуская мова biełaruskaja mova"),
        "bh": ("bih", "Bihar"), "bi": ("bis", "Bislama"), "bs": ("bos", "босански"), "br": ("bre", "Breton"),
        "bg": ("bul", "български"), "yue": ("chi", "粵語"), "yue-HK": ("chi", "粵語（中國香港）"), "ca": ("cat", "català"),
        "chr": ("chr", "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ"), "cho": ("cho", "Chahta'"), "co": ("cos", "lingua corsa"), "hr": ("hrv", "Hrvatska"),
        "cs": ("cze", "čeština"), "da": ("dan", "Dansk"), "nl": ("dut", "Nederlands"), "nl-BE": ("dut", "Nederlands(Belgisch)"),
        "nl-NL": ("dut", "Nederlands(Nederlands)"), "dz": ("dzo", "རྫོང་ཁ།"), "en": ("eng", "English"),
        "en-CA": ("eng", "English(Canada)"), "en-IE": ("eng", "English(Ireland)"), "en-GB": ("eng", "English(UK)"),
        "eo": ("epo", "Esperanto"), "et": ("est", "Eestlane"), "fo": ("fao", "føroyskt"), "fj": ("fij", "Vakaviti"),
        "fil": ("phi", "Pilipino"), "fi": ("fin", "Suomi"), "fr": ("fre", "Français"), "fr-BE": ("fre", "Français(Belgique)"),
        "fr-CA": ("fre", "Français(Canada)"), "fr-FR": ("fre", "Français(La France)"), "fr-CH": ("fre", "Français(Suisse)"),
        "ff": ("ful", "Fulani"), "gl": ("glg", "galego"), "ka": ("geo", "ქართული ენა"), "de": ("ger", "Deutsch"),
        "de-AT": ("ger", "Deutsch(Österreich)"), "de-DE": ("ger", "Deutsch(Deutschland)"), "de-CH": ("ger", "Deutsch(Schweiz)"),
        "el": ("gre", "Ελληνικά"), "kl": ("kal", "Kalaallisut"), "gn": ("grn", "avañe'ẽ"), "gu": ("guj", "ગુજરાતી"),
        "hak": ("hak", "Hak-kâ-fa"), "hak-TW": ("hak", "Hak-kâ-fa"), "ha": ("hau", "هَوُسَ"), "iw": ("heb", "שפה עברית"),
        "hi": ("hin", "हिन्दी"), "hi-Latn": ("hin", "हिंदी(फोनेटिक)"), "hu": ("hun", "Magyar"), "is": ("ice", "icelandic"),
        "ig": ("ibo", "Asụsụ Igbo"), "id": ("ind", "Indonesia"), "ia": ("ina", "Interlingua"), "iu": ("iku", "ᐃᓄᒃᑎᑐᑦ"),
        "ik": ("ipk", "Inupiat"), "ga": ("gle", "Gaeilge na hÉireann"), "it": ("ita", "Italiano"), "jv": ("jav", "ꦧꦱꦗꦮ"),
        "kn": ("kan", "ಕನ್ನಡ"), "ks": ("kas", "कॉशुर"), "kk": ("kaz", "Қазақ тілі"), "km": ("khm", "ភាសាខ្មែរ"),
        "rw": ("kin", "Ikinyarwanda"), "tlh": ("tlh", "tlhIngan Hol"), "ku": ("kur", "Kurdî"), "ky": ("kir", "кыргыз тили"),
        "lo": ("lao", "ພາສາລາວ"), "la": ("lat", "latīna"), "lv": ("lav", "latviešu valoda"), "ln": ("lin", "Lingála"),
        "lt": ("lit", "lietuvių kalba"), "lb": ("ltz", "Lëtzebuergesch"), "mk": ("mac", "Македонски јазик"),
        "mg": ("mlg", "maa.laa.gaas"), "ms": ("may", "Melayu"), "ml": ("mal", "മലയാളം"), "mt": ("mlt", "Lingwa Maltija"),
        "mi": ("mao", "Māori"), "mr": ("mar", "मराठी Marāṭhī"), "mas": ("mas", "Maasai"), "nan": ("nan", "閩南語"),
        "nan-TW": ("nan", "閩南語(台灣)"), "lus": ("lus", "Mizo ṭawng"), "mo": ("mol", "Limba moldovenească"),
        "mn": ("mon", "монгол хэл"), "my": ("bur", "မြန်မာဘာသာ"), "na": ("nau", "Dorerin Naoero"), "nv": ("nav", "Diné bizaad"),
        "ne": ("nep", "नेपाली Nepālī"), "no": ("nor", "norsk språk"), "fa": ("per", "فارسی"), "fa-AF": ("per", "فارسی"),
        "fa-IR": ("per", "فارسی"), "pl": ("pol", "Polski"), "pt": ("por", "Português"), "pt-BR": ("por", "Português(brasil)"),
        "pt-PT": ("por", "Português(portugal)"), "ro": ("rum", "Română"), "ru": ("rus", "Русский"),
        "ru-Latn": ("rus", "Русский(фонетический)"), "sr": ("srp", "Српски"), "sr-Cyrl": ("srp", "Српски(ћирилица)"),
        "sr-Latn": ("srp", "Српски(латиница)"), "sh": ("scr", "srpskohrvatski"), "sk": ("slo", "slovenský"),
        "es": ("spa", "Español"), "es-419": ("spa", "Español(Latinoamérica)"), "es-MX": ("spa", "Español(México)"),
        "es-ES": ("spa", "Español(España)"), "es-US": ("spa", "Español(Estados Unidos)"), "sv": ("swe", "Svenska"),
        "tl": ("tgl", "Tagalog"), "th": ("tha", "ไทย"), "tr": ("tur", "Türkçe"), "uk": ("ukr", "Українська"),
        "ur": ("urd", "Urdu"), "vi": ("vie", "Tiếng Việt"),
    ]

    // MARK: saving

    public static func save(_ sub: SubtitleInfo, http: HTTPClient = .shared, session: Session) async throws {
        let body = try await http.getString(sub.url, session: session)
        let text = sub.path.hasSuffix(".srt") ? try srt(fromJSON: body) : body
        try text.write(toFile: sub.path, atomically: true, encoding: .utf8)
    }

    static func srt(fromJSON text: String) throws -> String {
        let json = try JSON.parse(text)
        if json.has("events") { return YtDlp.srt(fromJSON3: json) }
        var out = ""
        for (i, line) in json["body"].array.enumerated() {
            out += "\(i + 1)\n"
            let from = line["from"].double ?? 0
            let to = line["to"].double ?? 0
            out += "\(srtTime(from)) --> \(srtTime(to))\n"
            if line.has("content") { out += line["content"].stringValue + "\n" }
            out += "\n"
        }
        return out
    }

    /// `hh:mm:ss,fff`
    static func srtTime(_ seconds: Double) -> String {
        let total = Int(seconds)
        let ms = Int((seconds - Double(total)) * 1000 + 0.5)
        return String(format: "%02d:%02d:%02d,%03d", total / 3600, (total % 3600) / 60, total % 60, ms)
    }
}
